-- =====================================================================
-- Oja: Bumpa-style commerce platform — database (Stage 1)
-- Paste this whole file into Supabase > SQL Editor > New query > Run.
-- It creates every table the first stages need, so later stages only
-- add to it.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------- Stores: one per seller ----------
create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9-]{3,40}$'),
  category text,
  description text,
  whatsapp text,
  phone text,
  address text,
  logo_url text,
  brand_color text not null default '#1B2A57',
  is_published boolean not null default true,
  plan text not null default 'trial',               -- trial | starter | pro (billing comes in a later stage)
  trial_ends_at timestamptz not null default (now() + interval '14 days'),
  created_at timestamptz not null default now()
);

-- ---------- Products ----------
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  compare_at_price numeric(12,2) check (compare_at_price is null or compare_at_price >= 0),
  stock integer not null default 0,
  image_urls text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists products_store_idx on public.products(store_id);

-- ---------- Customers ----------
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now()
);
create index if not exists customers_store_idx on public.customers(store_id);

-- ---------- Orders (website orders AND sales recorded by hand) ----------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  order_number bigint generated by default as identity,
  channel text not null default 'website'
    check (channel in ('website','whatsapp','instagram','walk_in','other')),
  status text not null default 'pending'
    check (status in ('pending','processing','shipped','delivered','cancelled')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid','paid','refunded')),
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists orders_store_idx on public.orders(store_id, created_at desc);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  name text not null,
  price numeric(12,2) not null,
  quantity integer not null check (quantity > 0)
);
create index if not exists order_items_order_idx on public.order_items(order_id);

-- ---------- Expenses ----------
create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  title text not null,
  amount numeric(12,2) not null check (amount >= 0),
  spent_on date not null default current_date,
  created_at timestamptz not null default now()
);

-- =====================================================================
-- Security: each seller can only see and change their own data.
-- Shoppers can only read published stores and active products.
-- =====================================================================
create or replace function public.owns_store(sid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.stores where id = sid and owner_id = auth.uid());
$$;

alter table public.stores      enable row level security;
alter table public.products    enable row level security;
alter table public.customers   enable row level security;
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;
alter table public.expenses    enable row level security;

create policy "stores: public read published" on public.stores
  for select using (is_published or owner_id = auth.uid());
create policy "stores: owner insert" on public.stores
  for insert with check (owner_id = auth.uid());
create policy "stores: owner update" on public.stores
  for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy "products: public read active" on public.products
  for select using (
    is_active and exists (select 1 from public.stores s where s.id = store_id and s.is_published)
  );
create policy "products: owner manage" on public.products
  for all using (public.owns_store(store_id)) with check (public.owns_store(store_id));

create policy "customers: owner manage" on public.customers
  for all using (public.owns_store(store_id)) with check (public.owns_store(store_id));

create policy "orders: owner manage" on public.orders
  for all using (public.owns_store(store_id)) with check (public.owns_store(store_id));

create policy "order_items: owner manage" on public.order_items
  for all using (exists (select 1 from public.orders o where o.id = order_id and public.owns_store(o.store_id)))
  with check (exists (select 1 from public.orders o where o.id = order_id and public.owns_store(o.store_id)));

create policy "expenses: owner manage" on public.expenses
  for all using (public.owns_store(store_id)) with check (public.owns_store(store_id));

-- =====================================================================
-- Photo storage (logos + product photos). Each seller uploads into a
-- folder named after their user id.
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('store-media', 'store-media', true)
on conflict (id) do nothing;

create policy "store-media: owner upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'store-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "store-media: owner update" on storage.objects
  for update to authenticated
  using (bucket_id = 'store-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "store-media: owner delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'store-media' and (storage.foldername(name))[1] = auth.uid()::text);
