import { redirect } from "next/navigation";
import Link from "next/link";
import { Activity, BadgeCheck, Banknote, Building2, CheckCircle2, CircleDollarSign, FileCheck2, Flag, History, Landmark, ShieldCheck, Store, Users, WalletCards, XCircle } from "lucide-react";
import { requireAdmin } from "@/lib/admin";
import { formatNaira } from "@/lib/utils";
import { paymentConfigStatus } from "@/lib/payments/transactpay";
import AdminActionForm from "@/components/AdminActionForm";
import AdminDecisionForm from "@/components/AdminDecisionForm";
import AdminSettingForm from "@/components/AdminSettingForm";
import AdminVerificationForm from "@/components/AdminVerificationForm";
import AdminPaymentSettingsForm from "@/components/AdminPaymentSettingsForm";
import AdminMenu from "@/components/AdminMenu";
import AdminHoldForm from "@/components/AdminHoldForm";

export const dynamic = "force-dynamic";

const storeFields = "id,owner_id,name,slug,category,address,legal_name,nin,nin_status,cac_number,cac_file_url,approval_status,rejection_reason,plan,trusted,verification_approved,completed_orders,created_at,is_published,trial_starts_at,trial_ends_at";
const money = (value) => formatNaira(Number(value || 0));

function Metric({ icon: Icon, label, value, detail, accent = false }) { return <div className={`app-card p-5 ${accent ? "border-kola/30 bg-kola-light" : ""}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-muted">{label}</p><p className="mt-3 text-2xl font-extrabold">{value}</p>{detail && <p className="mt-1 text-[11px] text-muted">{detail}</p>}</div><span className={`grid h-10 w-10 place-items-center rounded-2xl ${accent ? "bg-kola text-white" : "bg-surface text-kola"}`}><Icon size={18} /></span></div></div>; }
function SectionTitle({ eyebrow, title, count }) { return <div className="flex flex-wrap items-end justify-between gap-3 border-b border-line pb-4"><div><p className="eyebrow text-kola">{eyebrow}</p><h2 className="display mt-2 text-2xl">{title}</h2></div>{count !== undefined && <span className="chip">{count}</span>}</div>; }
function Status({ value }) { const colour = value === "approved" || value === "sent" || value === "resolved" || value === "verified" || value === "paid" ? "text-success bg-green-50" : value === "rejected" || value === "refunded" ? "text-danger bg-red-50" : "text-warning bg-amber-50"; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ${colour}`}>{value || "pending"}</span>; }

async function AdminContent() {
  const { user, authorized, supabase } = await requireAdmin();
  if (!user) redirect("/login?next=/admin");
  if (!authorized) return <div className="min-h-screen bg-surface px-5 py-12"><div className="mx-auto max-w-xl app-card p-7 sm:p-10"><p className="eyebrow text-kola">Admin access</p><h1 className="display mt-3 text-3xl">This account is not an admin</h1><p className="mt-4 text-sm leading-6 text-muted">You are signed in as <strong className="text-ink">{user.email}</strong>, but this email is not in Sella&apos;s platform admin registry.</p><div className="mt-6 rounded-2xl bg-surface p-4 text-sm leading-6"><p className="font-extrabold">Add the exact email to public.platform_admins</p><p className="mt-2 text-muted">An existing platform admin can add it in Supabase, then sign out and sign in again before opening /admin.</p></div><Link href="/dashboard" className="btn-primary mt-6 inline-flex">Seller dashboard</Link></div></div>;
  const { data: snapshot, error: snapshotError } = await supabase.rpc("admin_dashboard_snapshot");
  if (snapshotError) throw snapshotError;
  const stores = snapshot?.stores || [];
  const orders = snapshot?.orders || [];
  const subscriptions = snapshot?.subscriptions || [];
  const withdrawals = snapshot?.withdrawals || [];
  const reports = snapshot?.reports || [];
  const settings = snapshot?.settings || [];
  const events = snapshot?.events || [];
  const auditLogs = snapshot?.audit_logs || [];
  const wallets = snapshot?.wallets || [];
  const accounts = snapshot?.accounts || [];
  const warning = "";
  const paymentStatus = await paymentConfigStatus();
  const pending = stores.filter((store) => store.approval_status === "pending" || (!store.approval_status && !store.is_published));
  const active = stores.filter((store) => store.approval_status === "approved" && store.is_published);
  const openReports = reports.filter((report) => report.status !== "resolved");
  const openWithdrawals = withdrawals.filter((item) => item.status === "pending");
  const paidOrders = orders.filter((order) => order.payment_status === "paid");
  const paidSubscriptions = subscriptions.filter((subscription) => subscription.status === "paid" || subscription.status === "active");
  const commissionRevenue = paidOrders.reduce((sum, order) => sum + Number(order.commission || 0), 0);
  const subscriptionRevenue = paidSubscriptions.reduce((sum, subscription) => sum + Number(subscription.amount || 0), 0);
  const grossRevenue = paidOrders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  const orderCounts = orders.reduce((counts, order) => ({ ...counts, [order.store_id]: (counts[order.store_id] || 0) + 1 }), {});
  const commission = settings.find((item) => item.key === "commission_rate")?.value?.rate || 5;

  return <div className="min-h-screen bg-surface">
    <header className="sticky top-0 z-50 border-b border-line bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="text-base font-extrabold tracking-tight text-kola">Sella<span className="text-mango">.</span> Admin</Link><div className="flex items-center gap-2 sm:gap-3"><span className="hidden text-xs text-muted sm:inline">{user.email}</span><Link href="/dashboard" className="btn-soft px-3 py-2 text-xs">Seller dashboard</Link><AdminMenu /></div></div></header>
    <main className="mx-auto max-w-[1240px] space-y-10 px-5 py-8 sm:px-8 sm:py-12">
      <div><p className="eyebrow text-kola">Private workspace</p><h1 className="display mt-3 text-4xl sm:text-5xl">Platform control room</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted">Review sellers, protect buyers, manage trust, monitor money, and keep the marketplace moving.</p></div>
      {warning && <div className="rounded-[22px] border border-warning/30 bg-amber-50 p-5 text-sm text-warning"><div className="flex items-start gap-3"><Activity size={19} className="mt-0.5 shrink-0" /><div><strong>Privileged database attention needed.</strong><p className="mt-1 leading-6">{warning}. Add the production SUPABASE_SERVICE_ROLE_KEY in Vercel to enable full queues and actions.</p></div></div></div>}

      <section id="overview" className="scroll-mt-28 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Commission earned" value={money(commissionRevenue)} detail={`${paidOrders.length} paid orders`} accent /><Metric icon={Banknote} label="Subscription revenue" value={money(subscriptionRevenue)} detail={`${paidSubscriptions.length} paid plans`} /><Metric icon={Store} label="Stores" value={stores.length} detail={`${active.length} live · ${pending.length} pending`} /><Metric icon={Flag} label="Open attention" value={openReports.length + openWithdrawals.length} detail={`${openReports.length} reports · ${openWithdrawals.length} withdrawals`} /></section>

      <section className="grid gap-4 sm:grid-cols-3"><div className="app-card p-5"><p className="text-xs font-bold text-muted">Gross paid order value</p><p className="mt-2 text-xl font-extrabold">{money(grossRevenue)}</p></div><div className="app-card p-5"><p className="text-xs font-bold text-muted">Paid orders</p><p className="mt-2 text-xl font-extrabold">{paidOrders.length}</p></div><div className="app-card p-5"><p className="text-xs font-bold text-muted">Trusted sellers</p><p className="mt-2 text-xl font-extrabold">{stores.filter((store) => store.trusted).length}</p></div></section>

      <section id="orders" className="scroll-mt-28"><SectionTitle eyebrow="Platform money" title="Orders & revenue" count={`${orders.length} recent`} /><div className="app-card mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-line text-[11px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Order</th><th className="px-5 py-4">Store</th><th className="px-5 py-4">Total</th><th className="px-5 py-4">Commission</th><th className="px-5 py-4">Payment</th><th className="px-5 py-4">Escrow</th></tr></thead><tbody className="divide-y divide-line">{orders.length ? orders.slice(0, 50).map((order) => <tr key={order.id}><td className="px-5 py-4 text-sm font-extrabold">#{order.order_code || order.id.slice(0, 8)}</td><td className="px-5 py-4 text-xs font-bold">{order.stores?.name || "Store"}</td><td className="px-5 py-4 text-xs font-extrabold">{money(order.total)}</td><td className="px-5 py-4 text-xs">{money(order.commission)}</td><td className="px-5 py-4"><Status value={order.payment_status} /></td><td className="px-5 py-4"><Status value={order.escrow_status} /></td></tr>) : <tr><td colSpan="6" className="px-5 py-10 text-center text-sm text-muted">No orders yet.</td></tr>}</tbody></table></div></section>

      <section id="approvals" className="scroll-mt-28"><SectionTitle eyebrow="Seller review" title="Pending approvals" count={`${pending.length} awaiting`} /><div className="app-card mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="border-b border-line text-[11px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Store</th><th className="px-5 py-4">Business details</th><th className="px-5 py-4">NIN</th><th className="px-5 py-4">CAC</th><th className="px-5 py-4 text-right">Decision</th></tr></thead><tbody className="divide-y divide-line">{pending.length ? pending.map((store) => <tr key={store.id}><td className="px-5 py-5"><p className="text-sm font-extrabold">{store.name}</p><p className="mt-1 text-xs text-muted">/{store.slug} · {store.category || "No category"}</p></td><td className="px-5 py-5 text-xs leading-5 text-muted"><strong className="text-ink">{store.legal_name || "Legal name not submitted"}</strong><br />{store.address || "Address not submitted"}</td><td className="px-5 py-5 text-xs text-muted"><Status value={store.nin_status} />{store.nin && <p className="mt-2">{store.nin}</p>}</td><td className="px-5 py-5 text-xs text-muted">{store.cac_number || "Not submitted"}{store.cac_file_url && <a className="mt-2 block font-bold text-kola underline" href={store.cac_file_url} target="_blank" rel="noreferrer">View certificate</a>}</td><td className="px-5 py-5 text-right"><AdminDecisionForm storeId={store.id} /></td></tr>) : <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-muted">No sellers are waiting for approval.</td></tr>}</tbody></table></div></section>

      <section id="stores" className="scroll-mt-28"><SectionTitle eyebrow="Trust & verification" title="Store directory" count={`${stores.length} total`} /><div className="app-card mt-4 overflow-x-auto"><table className="w-full min-w-[1080px] text-left"><thead className="border-b border-line text-[11px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Store</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Trial</th><th className="px-5 py-4">Orders</th><th className="px-5 py-4">Trust</th><th className="px-5 py-4">Verification</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-line">{stores.map((store) => <tr key={store.id}><td className="px-5 py-5"><p className="text-sm font-extrabold">{store.name}</p><p className="mt-1 text-xs text-muted">/{store.slug}</p></td><td className="px-5 py-5 text-xs font-bold capitalize">{store.plan || "trial"}</td><td className="px-5 py-5 text-xs text-muted">{store.trial_ends_at ? new Date(store.trial_ends_at).toLocaleDateString() : "—"}</td><td className="px-5 py-5 text-xs font-bold">{orderCounts[store.id] || store.completed_orders || 0}</td><td className="px-5 py-5"><Status value={store.trusted ? "trusted" : "standard"} /></td><td id="verification" className="scroll-mt-28 px-5 py-5"><Status value={store.verification_approved ? "verified" : store.nin_status || "pending"} /></td><td className="px-5 py-5"><div className="flex flex-wrap justify-end gap-2"><AdminActionForm action="store_trust" field="storeId" value={store.id} nextValue={!store.trusted} label={store.trusted ? "Untrust" : "Trust"} /><AdminVerificationForm storeId={store.id} approved={store.verification_approved} /></div></td></tr>)}</tbody></table></div></section>

      <section id="accounts" className="scroll-mt-28"><SectionTitle eyebrow="Trust & safety" title="Buyer and seller accounts" count={`${accounts.length} accounts`} /><div className="app-card mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="border-b border-line text-[11px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Account</th><th className="px-5 py-4">Role details</th><th className="px-5 py-4">Joined</th><th className="px-5 py-4 text-right">Account control</th></tr></thead><tbody className="divide-y divide-line">{accounts.length ? accounts.map((account) => <tr key={account.user_id}><td className="px-5 py-5"><p className="text-sm font-extrabold">{account.buyer_profile?.full_name || account.email || "Sella account"}</p><p className="mt-1 text-xs text-muted">{account.email}</p></td><td className="px-5 py-5 text-xs leading-5 text-muted">{account.seller_store ? <><strong className="text-ink">Seller</strong> · {account.seller_store.name} · <Status value={account.seller_store.approval_status} /></> : <><strong className="text-ink">Buyer</strong>{account.buyer_profile?.whatsapp ? ` · ${account.buyer_profile.whatsapp}` : " · Profile incomplete"}</>}</td><td className="px-5 py-5 text-xs text-muted">{account.created_at ? new Date(account.created_at).toLocaleDateString() : "—"}</td><td className="px-5 py-5 text-right"><AdminHoldForm account={account} /></td></tr>) : <tr><td colSpan="4" className="px-5 py-10 text-center text-sm text-muted">No accounts found.</td></tr>}</tbody></table></div></section>

      <section className="grid gap-8 xl:grid-cols-2"><div id="withdrawals" className="scroll-mt-28"><SectionTitle eyebrow="Money" title="Withdrawal queue" count={`${openWithdrawals.length} pending`} /><div className="app-card mt-4 divide-y divide-line overflow-hidden">{withdrawals.length ? withdrawals.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="min-w-0"><p className="text-sm font-extrabold">{item.stores?.name || "Store"}</p><p className="mt-1 text-xs text-muted">{money(item.amount)} · {item.bank_name} · {item.account_number}</p><p className="mt-1 text-[11px] text-muted">{item.account_name || "Account name unavailable"} · {new Date(item.created_at).toLocaleString()}</p></div><div className="flex items-center gap-3"><Status value={item.status} />{item.status === "pending" && <div className="flex gap-2"><AdminActionForm action="withdrawal_status" field="withdrawalId" value={item.id} nextValue="sent" label="Mark sent" /><AdminActionForm action="withdrawal_status" field="withdrawalId" value={item.id} nextValue="rejected" label="Reject" /></div>}</div></div>) : <p className="p-8 text-center text-sm text-muted">No withdrawal requests.</p>}</div></div>
        <div id="reports" className="scroll-mt-28"><SectionTitle eyebrow="Trust & safety" title="Reports queue" count={`${openReports.length} open`} /><div className="app-card mt-4 divide-y divide-line overflow-hidden">{reports.length ? reports.map((report) => <div key={report.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-extrabold">{report.type} report · {report.stores?.name || "Store"}</p><p className="mt-1 text-xs text-muted">{report.reason} · {new Date(report.created_at).toLocaleString()}</p>{report.orders?.order_code && <p className="mt-1 text-xs text-muted">Order #{report.orders.order_code} · {money(report.orders.total)}</p>}{report.products?.name && <p className="mt-1 text-xs text-muted">Product: {report.products.name}</p>}{report.details && <p className="mt-3 rounded-xl bg-surface p-3 text-xs leading-5 text-muted">{report.details}</p>}</div><div className="flex items-center gap-3"><Status value={report.status} />{report.status !== "resolved" && <AdminActionForm action="report_status" field="reportId" value={report.id} nextValue="resolved" label="Resolve" />}</div></div></div>) : <p className="p-8 text-center text-sm text-muted">No reports.</p>}</div></div></section>

      <section id="subscriptions" className="scroll-mt-28"><SectionTitle eyebrow="Subscriptions" title="Seller plans" count={`${subscriptions.length} records`} /><div className="app-card mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-line text-[11px] font-extrabold uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Store</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Payment</th><th className="px-5 py-4">Period</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-line">{subscriptions.length ? subscriptions.map((subscription) => <tr key={subscription.id}><td className="px-5 py-5 text-sm font-extrabold">{subscription.stores?.name || "Store"}</td><td className="px-5 py-5 text-xs font-bold capitalize">{subscription.plan}</td><td className="px-5 py-5 text-xs font-extrabold">{money(subscription.amount)}</td><td className="px-5 py-5 text-xs capitalize text-muted">{subscription.paid_with}</td><td className="px-5 py-5 text-xs text-muted">{new Date(subscription.started_at).toLocaleDateString()} – {new Date(subscription.expires_at).toLocaleDateString()}</td><td className="px-5 py-5"><Status value={subscription.status || "pending"} /></td></tr>) : <tr><td colSpan="6" className="px-5 py-10 text-center text-sm text-muted">No subscription records yet.</td></tr>}</tbody></table></div></section>
      <section className="grid gap-8 xl:grid-cols-[1.1fr_.9fr]"><div id="settings" className="scroll-mt-28"><SectionTitle eyebrow="Platform settings" title="Commission & trust rules" /><div className="app-card mt-4 space-y-6 p-6"><div><p className="text-sm font-extrabold">Global commission rate</p><p className="mt-1 text-xs leading-5 text-muted">Current default: {commission}% on paid orders.</p><AdminSettingForm initialRate={commission} /></div><div className="border-t border-line pt-5"><p className="text-sm font-extrabold">Trust threshold</p><p className="mt-1 text-xs leading-5 text-muted">Set how many confirmed delivered orders a seller needs before automatic trust.</p><AdminSettingForm initialRate={settings.find((item) => item.key === "trusted_order_threshold")?.value?.count || 3} settingKey="trusted_order_threshold" label="Save threshold" /></div></div></div><div id="wallets" className="scroll-mt-28"><SectionTitle eyebrow="Seller balances" title="Wallet snapshot" count={`${wallets.length} wallets`} /><div className="app-card mt-4 divide-y divide-line overflow-hidden">{wallets.length ? wallets.slice(0, 8).map((wallet) => <div key={wallet.store_id} className="flex items-center justify-between gap-3 p-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-kola-light text-kola"><WalletCards size={16} /></span><p className="truncate text-sm font-bold">{wallet.stores?.name || "Store"}</p></div><div className="text-right"><p className="text-xs font-extrabold">{money(wallet.available)} available</p><p className="mt-1 text-[11px] text-muted">{money(wallet.held)} held</p></div></div>) : <p className="p-8 text-center text-sm text-muted">No seller wallets yet.</p>}</div></div></section>

      <section id="payments" className="scroll-mt-28"><SectionTitle eyebrow="Payments" title="TransactPay configuration" /><div className="app-card mt-4 p-6"><div className="mb-5 flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-mango text-kola-dark"><Landmark size={19} /></span><div><p className="text-sm font-extrabold">Virtual accounts and order transfers</p><p className="mt-1 max-w-2xl text-xs leading-5 text-muted">Keys are encrypted before storage and are never displayed after saving. Leave a field blank to keep its existing value.</p></div></div><AdminPaymentSettingsForm status={paymentStatus} /></div></section>

      <section id="activity" className="scroll-mt-28 grid gap-8 xl:grid-cols-2"><div><SectionTitle eyebrow="Payment events" title="Webhook activity" count={`${events.length} recent`} /><div className="app-card mt-4 divide-y divide-line overflow-hidden">{events.length ? events.map((event) => <div key={event.id} className="flex items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-kola-light text-kola"><Activity size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold">{event.event_key}</p><p className="mt-1 text-[11px] text-muted">{event.provider} · {new Date(event.received_at).toLocaleString()}</p></div><CheckCircle2 size={16} className="text-success" /></div>) : <p className="p-8 text-center text-sm text-muted">No webhook events received yet.</p>}</div></div><div><SectionTitle eyebrow="Audit" title="Admin activity" count={`${auditLogs.length} recent`} /><div className="app-card mt-4 divide-y divide-line overflow-hidden">{auditLogs.length ? auditLogs.map((log) => <div key={log.id} className="flex items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-surface text-kola"><History size={16} /></span><div><p className="text-xs font-extrabold">{log.action}</p><p className="mt-1 text-[11px] text-muted">{new Date(log.created_at).toLocaleString()}</p></div></div>) : <p className="p-8 text-center text-sm text-muted">No admin actions recorded yet.</p>}</div></div></section>
      <section id="notifications" className="scroll-mt-28"><SectionTitle eyebrow="Alerts" title="Notifications" /><div className="app-card mt-4 flex flex-wrap items-center justify-between gap-4 p-6"><div><p className="text-sm font-extrabold">Platform notifications</p><p className="mt-1 max-w-xl text-xs leading-5 text-muted">Review your Admin notifications and turn on browser or phone alerts for new seller submissions, reports, payment events, and account holds.</p></div><Link href="/admin/notifications" className="btn-primary">Open notifications</Link></div></section>
    </main>
  </div>;
}

export default async function AdminPage() {
  try {
    return await AdminContent();
  } catch (error) {
    if (String(error?.digest || "").startsWith("NEXT_REDIRECT") || error?.digest === "DYNAMIC_SERVER_USAGE") throw error;
    console.error("Admin page error", error);
    return <div className="min-h-screen bg-surface px-5 py-12"><div className="mx-auto max-w-xl app-card p-7 sm:p-10"><p className="eyebrow text-kola">Admin diagnostics</p><h1 className="display mt-3 text-3xl">Admin could not load</h1><p className="mt-4 text-sm leading-6 text-muted">The page reached Sella but the server could not load the Admin workspace. Confirm that your email is in the Supabase <code>platform_admins</code> table and that the authenticated Admin migrations have been applied.</p><div className="mt-5 rounded-2xl bg-surface p-4 text-xs leading-5 text-muted"><strong className="text-ink">Server message:</strong><br />{error?.message || "Unknown server exception"}</div><Link href="/dashboard" className="btn-primary mt-6 inline-flex">Seller dashboard</Link></div></div>;
  }
}
