\set ON_ERROR_STOP on
-- Disposable LOCAL DB only; fixtures model current production dependencies.
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function public.is_platform_admin() returns boolean language sql stable as $$select coalesce(current_setting('test.admin',true),'false')='true'$$;
create table stores(id uuid primary key,owner_id uuid references auth.users,name text);
create table orders(id uuid primary key,store_id uuid references stores,buyer_id uuid references auth.users,order_number text,total numeric);
create table chat_messages(id uuid primary key,conversation_id uuid);
create function public.can_access_chat(uuid) returns boolean language sql stable as $$select auth.uid()='11111111-1111-4111-8111-111111111111'::uuid$$;
create table reports(id uuid primary key default gen_random_uuid(),type text,store_id uuid references stores,order_id uuid references orders,reported_by uuid references auth.users,reason text,details text,status text default 'open',created_at timestamptz default now(),product_id uuid,message_id uuid references chat_messages, constraint reports_status_check check(status in('open','resolved')));
alter table reports enable row level security;
create policy "reports: reporter read own" on reports for select using(reported_by=auth.uid());
create policy "reports: seller read own store" on reports for select using(exists(select 1 from stores where id=store_id and owner_id=auth.uid()));
create table notifications(id uuid default gen_random_uuid(),user_id uuid,type text,title text,body text,link text);
create table storage.buckets(id text primary key,name text,public boolean);
create table storage.objects(id uuid,bucket_id text,name text);
alter table storage.objects enable row level security;
create function public.admin_apply_action(p_action text,p_payload jsonb default '{}') returns jsonb language plpgsql security definer as $$ begin if not public.is_platform_admin() then raise exception 'Admin required';end if;if p_action='report_status' then update reports set status=p_payload->>'status' where id=(p_payload->>'reportId')::uuid;end if;return '{"success":true}'::jsonb;end$$;
do $$begin if not exists(select 1 from pg_roles where rolname='service_role')then create role service_role bypassrls;end if;end$$;
alter role service_role bypassrls;
grant usage on schema auth,public,storage to authenticated,anon,service_role;
grant select on auth.users,stores,orders,chat_messages,storage.objects to authenticated,anon,service_role;
\ir ../supabase/stage-76-report-safety-cases.sql
create function expect_error(q text, expected text) returns void language plpgsql as $$ begin begin execute q; exception when others then if sqlerrm not ilike '%'||expected||'%' then raise exception 'Wrong failure: % expected %',sqlerrm,expected; end if; return; end; raise exception 'Expected failure: %',q; end $$;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222'),('33333333-3333-4333-8333-333333333333');
insert into stores values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','22222222-2222-4222-8222-222222222222','Store One');
insert into orders values('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','ORD12345',1000);
insert into chat_messages values('ffffffff-ffff-4fff-8fff-ffffffffffff','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
set role service_role;
insert into reports(id,type,store_id,order_id,reported_by,buyer_id,reason,report_reason,details) values('dddddddd-dddd-4ddd-8ddd-dddddddddddd','order','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc','11111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111','suspected_fraud','suspected_fraud','Private buyer details'),('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','store','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',null,'33333333-3333-4333-8333-333333333333','33333333-3333-4333-8333-333333333333','other_concern','other_concern','Other buyer details');
insert into report_evidence(report_id,uploaded_by,storage_path,file_name,mime_type,byte_size)values('dddddddd-dddd-4ddd-8ddd-dddddddddddd','11111111-1111-4111-8111-111111111111','private/evidence.png','evidence.png','image/png',100);
reset role; set role authenticated;
select set_config('test.uid','11111111-1111-4111-8111-111111111111',false);
do $$begin if(select count(*)from reports)<>1 then raise exception 'Buyer isolation failed';end if;if(select count(*)from report_evidence)<>1 then raise exception 'Buyer evidence metadata denied';end if;end$$;
select expect_error($q$update reports set status='Closed'$q$,'permission denied');
select expect_error($q$insert into reports(type,store_id,reported_by,buyer_id,reason) values('store','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111','suspected_fraud')$q$,'row-level security');
select expect_error($q$insert into report_events(report_id,actor_id,visibility,event_type,body)values('dddddddd-dddd-4ddd-8ddd-dddddddddddd','11111111-1111-4111-8111-111111111111','buyer','status_change','Fake resolved')$q$,'permission denied');
insert into reports(type,store_id,reported_by,reason,message_id) values('message','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','Unsafe message','ffffffff-ffff-4fff-8fff-ffffffffffff');
select set_config('test.uid','22222222-2222-4222-8222-222222222222',false);
do $$begin if(select count(*)from reports)<>0 then raise exception 'Seller can read private buyer report';end if;if(select count(*)from report_evidence)<>0 then raise exception 'Seller evidence leak';end if;end$$;
select expect_error($q$insert into reports(type,store_id,reported_by,reason,message_id) values('message','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','22222222-2222-4222-8222-222222222222','Unsafe','ffffffff-ffff-4fff-8fff-ffffffffffff')$q$,'row-level security');
select expect_error($q$select report_admin_action('dddddddd-dddd-4ddd-8ddd-dddddddddddd','internal_note',null,'not admin')$q$,'Admin access');
select expect_error($q$select report_seller_response('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Unrequested response')$q$,'not awaiting');
select set_config('test.admin','true',false);
select report_admin_action('dddddddd-dddd-4ddd-8ddd-dddddddddddd','internal_note',null,'CONFIDENTIAL ADMIN NOTE');
select report_admin_action('dddddddd-dddd-4ddd-8ddd-dddddddddddd','seller_request',null,'Please share fulfilment context');
do $$begin if(select count(*)from report_events where visibility='admin')<>1 then raise exception 'Admin cannot read internal note';end if;if(select count(*)from report_evidence)<>1 then raise exception 'Admin evidence denied';end if;end$$;
select admin_apply_action('setting','{}');
select expect_error($q$select report_admin_action('dddddddd-dddd-4ddd-8ddd-dddddddddddd','status',null)$q$,'Invalid report status');
select set_config('test.admin','false',false);
select report_seller_response('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Actual seller response');
select expect_error($q$select report_seller_response('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Duplicate response')$q$,'not awaiting');
select set_config('test.uid','11111111-1111-4111-8111-111111111111',false);
do $$begin if exists(select 1 from report_events where visibility in('admin','seller')) then raise exception 'Private events leaked to buyer';end if;if(select status from reports where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd')<>'Under Review' then raise exception 'Status did not update';end if;end$$;
select set_config('test.admin','true',false);
select admin_apply_action('report_status','{"reportId":"dddddddd-dddd-4ddd-8ddd-dddddddddddd","status":"resolved"}');
reset role;
do $$begin
 if(select count(*)from notifications where user_id='11111111-1111-4111-8111-111111111111')<>3 then raise exception 'Missing meaningful status notices';end if;
 if(select count(*)from report_audit_log where report_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd')<>7 then raise exception 'Missing audit history';end if;
 if(select public from storage.buckets where id='report-evidence')then raise exception 'Evidence bucket is public';end if;
 if(select count(distinct case_ref)from reports)<>3 then raise exception 'Case references not unique';end if;
 raise notice 'PASS report tests: buyer/seller isolation, no direct case/status spoofing, legacy chat, role-checked review, private notes, seller requests/responses, buyer updates, audit, unique refs, private bucket';
end$$;
