import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '/home/ubuntu/sella-test-tools/node_modules/esbuild/lib/main.js';
import { chromium } from '/home/ubuntu/sella-test-tools/node_modules/playwright-core/index.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output='/tmp/sella-safety-ui';fs.mkdirSync(output,{recursive:true});
await build({entryPoints:[path.join(repo,'tests/safety-ui.entry.jsx')],outfile:path.join(output,'bundle.js'),bundle:true,jsx:'automatic',loader:{'.js':'jsx'},define:{'process.env.NODE_ENV':'"test"'},alias:{'@':repo},plugins:[{name:'next-stubs',setup(b){b.onResolve({filter:/^@\/lib\/supabase\/client$/},()=>({path:'auth-mock',namespace:'auth-mock'}));b.onLoad({filter:/.*/,namespace:'auth-mock'},()=>({contents:'export function createClient(){return {auth:{async signUp(payload){window.__signup=payload;return {data:{user:{id:"test-user"},session:null},error:null}}}}}'}));b.onResolve({filter:/^next\/(navigation|link|image)$/},args=>({path:args.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},args=>({contents:args.path.endsWith('navigation')?'export function useRouter(){return {refresh(){window.__refreshed=true},push(url){window.__push=url}}}; export function usePathname(){return "/account"};':args.path.endsWith('link')?'import React from "react"; export default function Link({children,...props}) {return <a {...props}>{children}</a>}':'import React from "react"; export default function Image(props){return <img {...props}/>} ',loader:'jsx',resolveDir:repo}));}}]});
const html='<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"></head><body style="margin:0;padding:16px"><div id="root"></div><script src="/bundle.js"></script></body></html>';
const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':req.url==='/styles.css'?'text/css':'text/html');res.end(req.url==='/bundle.js'?fs.readFileSync(path.join(output,'bundle.js')):req.url==='/styles.css'?fs.readFileSync(path.join(output,'styles.css')):html)}).listen(4182,'127.0.0.1');
let browser;const results=[];const assert=(v,m)=>{if(!v)throw Error(m)};
try {
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});let posts=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4182?mode=signup');await page.getByRole('heading',{name:'Shop with confidence'}).waitFor();await page.getByLabel('Email',{exact:true}).fill('test@example.test');await page.getByLabel('Password',{exact:true}).fill('local-test-only');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByText('Check your email',{exact:true}).waitFor();assert(await page.evaluate(()=>Boolean(window.__signup)&&!('storeId' in window.__signup.options.data)),'Signup requires store trust');results.push('Signup completes mocked auth flow with existing fields and no store trust; real email delivery not tested');
 await page.route('**/api/buyer/trust-notice?*',route=>route.fulfill({json:{store:{id:'33333333-3333-4333-8333-333333333333',name:'Safety Test Store',sellerCode:'TEST1234',slug:'test',logoUrl:null},nonce:'test-signed-nonce',noticeVersion:'2026-09-16-v1'}}));
 await page.route('**/api/buyer/follow',route=>{posts.push(route.request().postDataJSON());return route.fulfill({json:{success:true,trusted:route.request().postDataJSON().follow}})});
 await page.goto('http://127.0.0.1:4182');await page.getByRole('button',{name:/Trust this store/i}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();await dialog.getByText('Safety Test Store',{exact:true}).waitFor();await dialog.getByText('Store ID: TEST1234',{exact:true}).waitFor();assert(await dialog.getByRole('button',{name:'Trust Store',exact:true}).isDisabled(),'Confirmation enabled before ack');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert(posts.length===0,'Cancel sent follow write');results.push('Correct store identity; unchecked confirmation disabled; cancel made no trust write');
 await page.getByRole('button',{name:/Trust this store/i}).click();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Trust Store',exact:true}).click();await page.getByRole('status').filter({hasText:'Store added to My Trusted Stores.'}).waitFor();assert(posts[0].acknowledged===true&&posts[0].noticeNonce,'Trust write missing acknowledgement/notice');results.push('Acknowledged confirmation submitted with notice nonce and success message');
 await page.goto('http://127.0.0.1:4182?mode=existing');assert(await page.getByRole('dialog').count()===0,'Existing trust repeated modal');results.push('Existing trust does not auto-open modal');
 await page.route('**/api/reports',route=>{posts.push('report');return route.fulfill({json:{report:{case_ref:'SLC-TEST1234'}}})});await page.goto('http://127.0.0.1:4182?mode=report');await page.getByRole('button',{name:/Report/}).click();await page.locator('select[name="reason"]').selectOption('order_not_received');await page.locator('textarea[name="details"]').fill('Local test order not received.');await page.getByRole('button',{name:'Submit report',exact:true}).click();await page.getByText(/SLC-TEST1234/).waitFor();results.push('Existing order ReportForm submits case and shows case reference without JS reset errors');
 await page.goto('http://127.0.0.1:4182?mode=first');await page.getByText('Buying from Safety Test Store').waitFor();assert(await page.getByRole('dialog').count()===0,'Checkout reminder blocked UI');await page.goto('http://127.0.0.1:4182?mode=returning');assert(await page.getByText('Buying from Safety Test Store').count()===0,'Returning buyer shown first purchase reminder');results.push('First-purchase information is inline; returning customer reminder omitted');
 await page.route('**/api/admin',route=>{posts.push(route.request().postDataJSON());return route.fulfill({json:{success:true}})});await page.goto('http://127.0.0.1:4182?mode=payout');await page.getByRole('button',{name:'Confirm bank settlement',exact:true}).click();assert(await page.getByRole('button',{name:'Record payout completed',exact:true}).isDisabled(),'Payout completion lacks bank-check gate');await page.locator('[name="channel"]').fill('Test bank');await page.locator('[name="reference"]').fill('LOCAL-TEST');await page.locator('[name="amount"]').fill('900');await page.locator('[name="paidAt"]').fill('2026-09-16T20:00');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Record payout completed',exact:true}).click();assert(posts.at(-1).confirmation.bank_success_checked===true,'Bank attestation missing');results.push('Manual bank settlement confirmation needs checkbox and exact-channel details before sending');
 assert(errors.length===0,errors.join('; '));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile horizontal overflow');results.push('No browser runtime errors; no horizontal overflow at 390px');
 fs.writeFileSync(path.join(repo,'tests/safety-ui-results.json'),JSON.stringify({scope:'Isolated real component tests with mocked API; not live signed-in transactions',passed:results},null,2)+'\n');console.log(results.join('\n'));
}finally{await browser?.close();server.close()}
