import { getMyStore } from "@/lib/store";
import { formatNaira } from "@/lib/utils";
import SubscriptionForm from "@/components/SubscriptionForm";

const plans = [{ id: "quarterly", label: "3 months", amount: 5000 }, { id: "biannual", label: "6 months", amount: 9000 }, { id: "yearly", label: "12 months", amount: 15000 }];

export default async function BillingPage() {
  const { supabase, store } = await getMyStore();
  const { data: subscriptions } = await supabase.from("subscriptions").select("plan,amount,paid_with,started_at,expires_at,status,payment_reference,paid_at").eq("store_id", store.id).order("started_at", { ascending: false }).limit(10);
  const trialDays = store.trial_starts_at ? Math.max(0, Math.ceil((new Date(store.trial_ends_at) - new Date()) / 86400000)) : null;
  return <div className="space-y-6"><div><p className="eyebrow text-kola">Plans & billing</p><h1 className="display mt-2 text-3xl">Keep your store moving</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Approved sellers receive a 10-day store trial. When you choose a plan, Sella creates a one-time TransactPay account number for the exact plan amount. Your plan upgrades after payment confirmation.</p></div>{trialDays !== null && <div className="rounded-2xl bg-kola-light p-4 text-sm text-kola"><strong>{trialDays} days remain</strong> in your 10-day trial. Explore the plans below before it ends.</div>}<div className="grid gap-4 md:grid-cols-3">{plans.map((plan) => <div key={plan.id} className="panel"><p className="font-semibold">{plan.label}</p><p className="mt-2 text-2xl font-bold">{formatNaira(plan.amount)}</p><p className="mt-1 text-sm text-muted">One-time bank transfer. Confirmed by TransactPay.</p><div className="mt-4"><SubscriptionForm storeId={store.id} plan={plan.id} amount={plan.amount} /></div></div>)}</div><section className="panel"><h2 className="font-semibold">Subscription history</h2><div className="mt-4 space-y-3">{subscriptions?.length ? subscriptions.map((item, index) => <div key={`${item.plan}-${index}`} className="flex flex-wrap justify-between gap-2 border-b border-line pb-3 text-sm"><span className="capitalize">{item.plan} · {item.paid_with}</span><span className={item.status === "paid" ? "font-bold text-success" : "text-muted"}>{item.status || "pending"}</span></div>) : <p className="text-sm text-muted">No subscription payments yet.</p>}</div></section></div>;
}
