import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, MapPin, Package, ShieldCheck } from "lucide-react";
import { getPublicStore, getPublicProducts } from "@/lib/storefront";
import { formatNaira, storeUrl } from "@/lib/utils";
import { getCurrentUser } from "@/lib/auth";
import PublicBottomNav from "@/components/PublicBottomNav";
import SellaBrand from "@/components/SellaBrand";
import BuyerHomeLink from "@/components/BuyerHomeLink";
import LiveWorkspaceRefresh from "@/components/LiveWorkspaceRefresh";
import TrustStoreButton from "@/components/TrustStoreButton";
import InstallPrompt from "@/components/InstallPrompt";

export const revalidate = 0;
export const dynamic = "force-dynamic";
export const dynamicParams = true;

export async function generateMetadata({ params }) {
  const store = await getPublicStore(params.slug);
  return store ? { title: `${store.name} on Sella`, description: store.description || `Shop ${store.name}` } : { title: "Store not found" };
}

export default async function StorePage({ params }) {
  const store = await getPublicStore(params.slug);
  if (!store) notFound();
  if (store.approval_status !== "approved") return <div className="flex min-h-screen items-center justify-center bg-surface px-4 py-10"><div className="app-card max-w-lg p-8 text-center sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-[22px] bg-kola-light text-kola"><ShieldCheck size={28} /></div><p className="eyebrow mt-6 text-kola">Sella verification</p><h1 className="display mt-3 text-3xl">This store is being verified</h1><p className="mt-4 text-sm leading-6 text-muted">{store.name} has submitted its details to Sella Team. The store will open to buyers after verification is complete.</p><p className="mt-6 text-xs font-bold text-muted">Please check back soon.</p></div></div>;
  if (store.order_access_suspended || store.seller_code_active === false) return <div className="flex min-h-screen items-center justify-center bg-surface px-4 py-10"><div className="app-card max-w-lg p-8 text-center sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-[22px] bg-amber-50 text-warning"><ShieldCheck size={28} /></div><p className="eyebrow mt-6 text-warning">Sella review</p><h1 className="display mt-3 text-3xl">This store is temporarily unavailable</h1><p className="mt-4 text-sm leading-6 text-muted">Sella Team is reviewing reports or account information for {store.name}. New orders are paused until the review is complete.</p><p className="mt-6 text-xs font-bold text-muted">Please check back later.</p></div></div>;
  const { supabase, user } = await getCurrentUser();
  const { data: existingTrust } = user ? await supabase.from("buyer_store_follows").select("id").eq("user_id", user.id).eq("store_id", store.id).maybeSingle() : { data: null };
  const products = (await getPublicProducts(store.id)).slice(0, 5);
  const singleProduct = products.length === 1;
  const storeHref = process.env.NODE_ENV === "production" ? `https://${store.slug}.${String(process.env.NEXT_PUBLIC_STORE_DOMAIN || "sella.com.ng").replace(/^https?:\/\//, "").replace(/\/+$/, "")}` : storeUrl("", store.slug);
  const setupPath = `/account/setup?returnTo=${encodeURIComponent(`/s/${store.slug}`)}`;
  return <div className="min-h-screen bg-surface pb-28"><InstallPrompt /><LiveWorkspaceRefresh scope="store" storeId={store.id} />
    <header className="bg-white"><div className="mx-auto max-w-[1120px] px-4 pb-8 pt-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between"><BuyerHomeLink ariaLabel="Back to Sella" className="grid h-10 w-10 place-items-center rounded-full bg-surface text-ink"><ArrowLeft size={19} /></BuyerHomeLink><SellaBrand href={storeHref} compact /><span className="w-10" /></div><div className="mt-8 flex flex-col items-center text-center">{store.logo_url ? <Image src={store.logo_url} alt={`${store.name} logo`} width={84} height={84} priority className="h-[84px] w-[84px] rounded-[26px] object-cover" /> : <div className="grid h-[84px] w-[84px] place-items-center rounded-[26px] bg-kola text-2xl font-extrabold text-white">{store.name.charAt(0).toUpperCase()}</div>}<h1 className="display mt-5 text-3xl sm:text-4xl">{store.name}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-muted"><MapPin size={15} /> {store.address || store.category || "Independent store"}</p>{store.description && <p className="mt-4 max-w-lg text-sm leading-6 text-muted">{store.description}</p>}{user ? <div className="mt-6"><TrustStoreButton storeId={store.id} initialTrusted={Boolean(existingTrust)} /><p className="mt-2 text-xs text-muted">Trusting this store adds its products to your Sella home feed and unlocks ordering.</p></div> : <><Link href={`/signup?role=customer&next=${encodeURIComponent(setupPath)}`} className="btn-primary mt-6">Create a buyer account to shop from {store.name}</Link><p className="mt-2 text-xs text-muted">This is for shopping, ordering, and tracking your purchases.</p></>}</div><div className="mt-8 grid grid-cols-3 divide-x divide-line rounded-[22px] bg-kola-light px-3 py-4 text-center"><div><p className="text-base font-extrabold text-kola">{products.length}</p><p className="mt-1 text-[10px] font-bold text-muted">FEATURED PRODUCTS</p></div><div><p className="text-base font-extrabold text-kola">Open</p><p className="mt-1 text-[10px] font-bold text-muted">STORE</p></div><div><ShieldCheck size={18} className="mx-auto text-kola" /><p className="mt-1 text-[10px] font-bold text-muted">SELLA SHOP</p></div></div></div></header>
    <main className="mx-auto max-w-[1120px] px-4 py-8 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow text-kola">Shop {store.name}</p><h2 className="display mt-2 text-2xl sm:text-3xl">Featured products</h2></div><span className="chip">{products.length} shown</span></div>{!products.length ? <div className="app-card mt-6 flex flex-col items-center px-6 py-12 text-center"><span className="grid h-14 w-14 place-items-center rounded-[20px] bg-kola-light text-kola"><Package size={23} /></span><h3 className="mt-5 text-base font-extrabold">Products are coming</h3><p className="mt-2 max-w-sm text-sm text-muted">{store.name} is preparing products for buyers.</p></div> : <div className={`mt-6 grid gap-x-4 gap-y-9 ${singleProduct ? "w-full max-w-[300px] grid-cols-1" : "grid-cols-2 md:grid-cols-3 lg:grid-cols-4"}`}>{products.map((product, index) => <article key={product.id} className="min-w-0"><a href={`${storeHref}/p/${product.id}`} className="group block"><div className="relative aspect-square overflow-hidden rounded-[22px] bg-white">{product.image_urls?.[0] ? <Image src={product.image_urls[0]} alt={product.name} fill priority={index < 2} sizes="(max-width: 768px) 50vw, 25vw" className="object-cover transition duration-300 group-hover:scale-[1.035]" /> : <div className="grid h-full place-items-center text-xs font-semibold text-muted">Product photo</div>}{product.stock <= 0 && <span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1.5 text-[10px] font-extrabold text-danger">SOLD OUT</span>}</div><div className="mt-3 flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{product.name}</p><p className="mt-1 text-xs text-muted">{product.stock > 0 ? `${product.stock} available` : "Unavailable"}</p></div><p className="shrink-0 text-sm font-extrabold text-kola">{formatNaira(product.price)}</p></div></a></article>)}</div>}{products.length === 5 && <div className="mt-8 text-center"><Link href={`/signup?role=customer&next=${encodeURIComponent(setupPath)}`} className="btn-soft">Create a buyer account to shop from {store.name}</Link><p className="mt-2 text-xs text-muted">Buyer account only — for shopping and ordering.</p></div>}</main>
    <footer className="mt-8 border-t border-line bg-white"><div className="mx-auto flex max-w-[1120px] flex-col gap-4 px-4 py-8 text-xs text-muted sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><div><p className="font-bold text-ink">{store.name}</p><p className="mt-1">Powered by Sella</p></div><Link href="/signup" className="font-bold text-kola">Create your own store</Link></div></footer><PublicBottomNav />
  </div>;
}
