"use client";
import { useState } from "react";

export default function AdminPaymentSettingsForm({ status }) {
  const [form, setForm] = useState({ baseUrl: status.baseUrl || "https://payment-api-service.transactpay.ai", publicKey: "", secretKey: "", encryptionKey: "" });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  function update(key) { return (event) => setForm((current) => ({ ...current, [key]: event.target.value })); }
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "payment_config", ...form }) }); const data = await response.json().catch(() => ({})); setBusy(false); setMessage(response.ok ? "Payment settings saved securely." : data.error || "Unable to save settings."); if (response.ok) setForm((current) => ({ ...current, publicKey: "", secretKey: "", encryptionKey: "" })); }
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Base URL</label><input className="input" value={form.baseUrl} onChange={update("baseUrl")} /></div><div><label className="label">Public key</label><input className="input" value={form.publicKey} onChange={update("publicKey")} placeholder={status.publicKey ? "Saved — leave blank to keep" : "Paste public key"} /></div><div><label className="label">Secret key</label><input className="input" type="password" value={form.secretKey} onChange={update("secretKey")} placeholder={status.secretKey ? "Saved — leave blank to keep" : "Paste secret key"} /></div><div><label className="label">Encryption key</label><textarea className="input min-h-24" value={form.encryptionKey} onChange={update("encryptionKey")} placeholder={status.encryptionKey ? "Saved — leave blank to keep" : "Paste RSA encryption key"} /></div></div><div className="flex flex-wrap items-center gap-4"><button className="btn-primary" disabled={busy}>{busy ? "Saving…" : "Save payment settings"}</button><span className="text-xs text-muted">{status.publicKey ? "Public key ready" : "Public key missing"} · {status.encryptionKey ? "Encryption key ready" : "Encryption key missing"}{status.updatedAt ? ` · Updated ${new Date(status.updatedAt).toLocaleDateString()}` : ""}</span></div>{message && <p className="text-sm text-muted">{message}</p>}</form>;
}
