"use client";
import Link from "next/link";
import { ArrowRight, BarChart3, Menu, Package, ShoppingBag, WalletCards, X } from "lucide-react";
import { useState } from "react";
import SellaBrand from "@/components/SellaBrand";
import { useHomepageMode } from "@/components/HomepageMode";

export default function HomepageTop({ signupHref = "/signup" }) {
  const { mode, setMode } = useHomepageMode();
  const [menuOpen, setMenuOpen] = useState(false);
  const demoSelected = mode === "demo";
  return <>
    <header className="seller-site-header"><div className="seller-wrap seller-nav"><SellaBrand /><nav className="seller-navlinks seller-desktop-links" aria-label="Main navigation"><Link href="#features">Product</Link><Link href="#how-it-works">Solutions</Link><Link href="#pricing">Pricing</Link><Link href="/faq">Resources</Link></nav><nav className="seller-navlinks" aria-label="Account navigation"><Link className="seller-plain-link" href="/login?next=%2Fdashboard">Sign in</Link><Link className="seller-button seller-button-primary seller-button-sm" href={signupHref}>Start selling free <ArrowRight size={15} /></Link><button type="button" className="seller-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open menu" aria-expanded={menuOpen}><Menu size={22} /></button></nav></div><div className="seller-company-bar"><p>Sella is owned and operated by Jojokev Digital - BN9832074</p></div></header>
    {menuOpen && <div className="seller-menu-popover" role="dialog" aria-modal="true" aria-label="Sella menu"><div className="seller-menu-inner"><div className="seller-menu-head"><div><p className="seller-eyebrow">Explore Sella</p><p className="seller-menu-title">A clearer way to run your store.</p></div><button type="button" className="seller-menu-button" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X size={22} /></button></div><nav className="seller-menu-links" aria-label="Information pages"><Link href="#features" onClick={() => setMenuOpen(false)}>Product <ArrowRight size={17} /></Link><Link href="/how-it-works" onClick={() => setMenuOpen(false)}>How It Works <ArrowRight size={17} /></Link><Link href="/faq" onClick={() => setMenuOpen(false)}>FAQ <ArrowRight size={17} /></Link><Link href="/book-a-demo" onClick={() => setMenuOpen(false)}>Book a Demo <ArrowRight size={17} /></Link></nav></div></div>}
    <section className="seller-hero"><div className="seller-wrap seller-hero-grid"><div><div className="seller-eyebrow">For Nigerian businesses</div><h1>{demoSelected ? "See how Sella can simplify your business." : <>Sell. Manage. <span>Grow.</span><br />All in one place.</>}</h1><p className="seller-lede">{demoSelected ? "Book a free 30-minute WhatsApp call and our team will personally walk you through setting up your store." : "Sella helps Nigerian businesses create online stores, manage products, receive payments, track orders and run their business with ease."}</p><div className="seller-hero-ctas">{demoSelected ? <><Link className="seller-button seller-button-primary" href={signupHref}>Try Sella <ArrowRight size={17} /></Link><Link className="seller-button seller-button-outline" href="/book-a-demo">Book a Demo <ArrowRight size={17} /></Link></> : <><Link className="seller-button seller-button-primary" href={signupHref}>Start selling free <ArrowRight size={17} /></Link><button type="button" className="seller-button seller-button-outline" onClick={() => setMode("demo")}>See how it works <ArrowRight size={17} /></button></>}</div><div className="seller-hero-proof"><span className="seller-proof-dots"><i /><i /><i /><i /></span><span>Join Nigerian sellers running their business with more clarity.</span></div></div>{!demoSelected && <div className="seller-hero-dashboard"><div className="seller-dashboard-preview-head"><span><b>Sella</b> seller dashboard</span><span className="seller-pill seller-pill-green">Live today</span></div><div className="seller-dashboard-preview-metrics"><div><BarChart3 size={16} /><small>Total sales</small><strong>₦1,248,500</strong><em>↑ 12% this month</em></div><div><ShoppingBag size={16} /><small>Orders</small><strong>342</strong><em>↑ 18% this month</em></div><div><WalletCards size={16} /><small>Wallet</small><strong>₦320,450</strong><em>Available</em></div></div><div className="seller-dashboard-preview-chart"><div className="seller-preview-chart-label"><b>Sales trend</b><span>Last 30 days</span></div><div className="seller-chart-bars">{[32, 42, 37, 54, 48, 66, 58, 76, 69, 88, 82, 96].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div><div className="seller-dashboard-preview-list"><div><Package size={15} /><span>Recent orders</span><b>View all →</b></div><p><span>#SLL7821 · Chinedu Okafor</span><strong>₦24,500</strong></p><p><span>#SLL7820 · Amara Yusuf</span><strong>₦12,000</strong></p></div></div>}</div></section><div className="seller-benefit-strip"><div><ShoppingBag size={17} /><span><b>Online storefront</b><small>Beautiful and ready to share</small></span></div><div><WalletCards size={17} /><span><b>Wallet & payments</b><small>Secure and reliable</small></span></div><div><Package size={17} /><span><b>Order management</b><small>Track fulfilment with ease</small></span></div><div><BarChart3 size={17} /><span><b>Sales reports</b><small>Know your numbers</small></span></div></div>
  </>;
}
