import { Package, Truck } from "lucide-react";
import { getMyStore } from "@/lib/store";
import { formatNaira } from "@/lib/utils";
import OrderStatusForm from "@/components/OrderStatusForm";
import { DeliveryReleaseForm, CancelOrderForm } from "@/components/OperationsForm";

export default async function SellerOrdersPage() {
  const { supabase, store } = await getMyStore();
  const { data: orders } = await supabase.from("orders").select("id,order_code,total,status,payment_status,escrow_status,fulfilment_method,created_at,customers(name,phone,email,address),order_items(name,price,quantity)").eq("store_id", store.id).order("created_at", { ascending: false });
  return <div className="space-y-7">
    <header><p className="eyebrow text-kola">Fulfilment</p><h1 className="display mt-2 text-3xl">Orders</h1><p className="mt-2 text-sm text-muted">Move paid orders from confirmed to delivered.</p></header>
    <div className="space-y-4">{orders?.length ? orders.map((order) => <article key={order.id} className="app-card overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-4 p-5"><div className="flex min-w-0 items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-kola-light text-kola"><Package size={19} /></span><div><p className="text-sm font-extrabold">Order #{order.order_code}</p><p className="mt-1 text-xs text-muted">{order.customers?.name || "Customer"} · {order.customers?.phone || order.customers?.email}</p><p className="mt-2 text-[10px] font-extrabold uppercase tracking-wide text-kola">{order.payment_status} · {order.escrow_status}</p></div></div><div className="text-right"><p className="text-base font-extrabold">{formatNaira(order.total)}</p><div className="mt-2"><OrderStatusForm order={order} /></div></div></div><div className="grid gap-4 border-t border-line bg-surface/70 p-5 text-xs md:grid-cols-2"><div><p className="font-extrabold text-ink">Items</p><p className="mt-2 leading-5 text-muted">{order.order_items?.map((item) => `${item.quantity} × ${item.name}`).join(", ")}</p></div><div><p className="flex items-center gap-2 font-extrabold text-ink"><Truck size={15} className="text-kola" />{order.fulfilment_method}</p><p className="mt-2 leading-5 text-muted">{order.customers?.address || "Pickup details arranged with buyer"}</p></div></div>{order.payment_status === "paid" && order.escrow_status === "held" && <div className="grid gap-5 border-t border-line p-5 md:grid-cols-2"><div><p className="mb-3 text-xs font-extrabold">Confirm delivery</p><DeliveryReleaseForm orderId={order.id} /></div><div><p className="mb-3 text-xs font-extrabold">Need to cancel?</p><CancelOrderForm orderId={order.id} /></div></div>}</article>) : <div className="app-card flex flex-col items-center px-6 py-14 text-center"><span className="grid h-14 w-14 place-items-center rounded-[20px] bg-kola-light text-kola"><Package size={23} /></span><h2 className="mt-5 text-base font-extrabold">No orders yet</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted">New orders from your storefront will appear here with payment and delivery details.</p></div>}</div>
  </div>;
}
