import LegalDocument from "@/components/LegalDocument";

export const metadata = { title: "Seller Terms of Use — Sella" };

export default function SellerTermsPage() {
  return <LegalDocument audience="Seller" title="Seller Terms of Use" intro="These terms apply when you create and operate a Sella store, list products, receive orders, manage seller funds, and use Sella business tools." sections={[
    { heading: "1. Seller account and verification", body: "Provide complete, accurate, and current business, identity, address, contact, and payout information. Sella Team may review your NIN and submitted details before approving a store. A store remains private and cannot accept orders until approval." },
    { heading: "2. Free Starter plan", body: "After Sella approval, your store starts on the free Starter plan. Starter has no expiry and allows up to 40 active product listings. It includes the core store, order, wallet, withdrawal, and buyer-chat tools, subject to Sella's operational controls." },
    { heading: "3. Optional paid upgrades", body: "Paid plans are optional upgrades for sellers who need more capacity or a lower commission rate. Basic is 3 months for ₦7,500 with up to 150 active products and 2.8% commission per paid order; Plus is 6 months for ₦14,000 with up to 500 active products and 2.6% commission; Premium is 12 months for ₦25,000 with unlimited active products and 2.4% commission. Plan prices, durations, limits, and platform rules may be updated with notice." },
    { heading: "4. Store and product responsibility", body: "You are responsible for the legality, authenticity, quality, description, pricing, stock, cost and selling-price information, customer communication, delivery, pickup, refunds where applicable, and fulfilment of every product you list. You may only upload materials you own or are authorised to use." },
    { heading: "5. Full refunds for paid seller-side cancellations", body: "Keep product availability and inventory accurate before accepting paid orders. If you cancel a paid order because an item is unavailable, was not listed accurately, or for another seller-side reason, you are responsible for funding the buyer's full original payment amount. This includes the portion previously deducted as Sella's commission; Sella does not reverse or pay that commission back for a seller-side cancellation. If your available Sella balance is insufficient, you must fund the outstanding amount through the refund funding method shown in your account before the buyer's Sella wallet can be credited. A refund is not treated as complete until the buyer wallet credit succeeds." },
    { heading: "6. Orders, payments, and withdrawals", body: "Update order progress accurately and fulfil paid orders as agreed. The commission applied to a paid order follows the active plan on the relevant seller store. Available balances are not a promise of immediate withdrawal; seller payout requests may be reviewed and processed under Sella controls. A completed bank payout is not automatically reversed because an order is later cancelled; any valid refund obligation remains separately recorded and visible for resolution." },
    { heading: "7. Reports, enforcement, and suspension", body: "Sella may review reports and refund obligations, reject or pause verification, remove listings, restrict store access, pause new orders, hold an account, or retain records while investigating fraud, piracy, unsafe conduct, false information, payment abuse, unresolved refund obligations, or a breach of these terms. An ordinary complaint is not automatically treated as proof of fraud." },
    { heading: "8. Changes and contact", body: "Sella may update seller features, plans, commission rates, or these terms when the service or applicable requirements change. Questions should be sent through the support channel provided in your account." }
  ]} relatedHref="/seller-privacy" relatedLabel="Read Seller Privacy & Anti-Piracy Policy" />;
}
