import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleAlert, ExternalLink, Package, Share2, ShoppingBag, Sparkles, WalletCards } from "lucide-react";
import { getMyStore } from "@/lib/store";
import { formatNaira, storeUrl } from "@/lib/utils";
import { SITE_URL } from "@/lib/config";
import ShareStore from "@/components/ShareStore";
import CopyStoreLink from "@/components/CopyStoreLink";
import RefundActions from "@/components/RefundActions";

function StatusPill({ status }) {
  const tone = status === "delivered" ? "bg-green-50 text-success" : status === "cancelled" ? "bg-red-50 text-danger" : "bg-amber-50 text-warning";
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ${tone}`}>{status}</span>;
}

function Metric({ label, value, detail, icon: Icon, href, accent = false }) {
  return <Link href={href} className={`group min-w-0 rounded-[20px] border p-4 transition hover:-translate-y-0.5 sm:p-5 ${accent ? "border-kola bg-kola text-white" : "border-line bg-white"}`}>
    <div className="flex items-start justify-between gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${accent ? "bg-white/15" : "bg-kola-light text-kola"}`}><Icon size={17} /></span><ArrowRight size={15} className={accent ? "text-white/60" : "text-muted"} /></div>
    <p className={`mt-5 truncate text-[11px] font-bold uppercase tracking-wide ${accent ? "text-white/70" : "text-muted"}`}>{label}</p>
    <p className="mt-1 truncate text-2xl font-extrabold">{value}</p>
    <p className={`mt-1 truncate text-[10px] ${accent ? "text-white/70" : "text-muted"}`}>{detail}</p>
  </Link>;
}

export default async function DashboardHome() {
  const { supabase, store } = await getMyStore();
  const [{ data: snapshot, error: snapshotError }, { data: renewalReminder }] = await Promise.all([
    supabase.rpc("get_seller_dashboard_snapshot", { p_store_id: store.id }),
    supabase.rpc("create_combined_renewal_reminder", { p_store_id: store.id }),
  ]);
  if (snapshotError) throw snapshotError;
  const reminder = renewalReminder?.show ? renewalReminder : null;
  const productCount = Number(snapshot?.product_count || 0);
  const lowStockCount = Number(snapshot?.low_stock_count || 0);
  const openOrderCount = Number(snapshot?.open_order_count || 0);
  const recentOrders = snapshot?.recent_orders || [];
  const wallet = snapshot?.wallet || null;
  const activeSubscription = snapshot?.active_subscription || null;
  const lowStockProducts = snapshot?.low_stock_products || [];
  const refundRows = snapshot?.refund_rows || [];
  const paidSales = Number(snapshot?.metrics?.paid_sales || 0);
  const paidOrderCount = Number(snapshot?.metrics?.paid_orders || 0);
  const planName = activeSubscription ? ({ basic: "Basic", plus: "Plus", premium: "Premium", quarterly: "Basic", biannual: "Plus", yearly: "Premium" }[activeSubscription.plan] || activeSubscription.plan) : "Starter";
  const planLimit = { Starter: 40, Basic: 150, Plus: 500, Premium: null }[planName];
  const storeLink = storeUrl(SITE_URL, store.slug);
  const priorities = [
    { label: "Orders waiting for fulfilment", value: openOrderCount || 0, href: "/dashboard/orders", icon: ShoppingBag, tone: "text-kola" },
    { label: "Products need restocking", value: lowStockCount || 0, href: "/dashboard/products", icon: CircleAlert, tone: "text-warning" },
    { label: "Store setup checks", value: [(productCount || 0) > 0, !!store.logo_url, !!store.whatsapp].filter(Boolean).length, href: "/dashboard/settings", icon: Check, tone: "text-success" },
  ];
  return <div className="space-y-6 sm:space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4">
      <div><p className="eyebrow text-kola">Seller command centre</p><h1 className="display mt-2 text-3xl sm:text-4xl">Good morning, {store.name}.</h1><p className="mt-2 text-sm text-muted">Your next best actions, money and store health in one view.</p></div>
      <div className="hidden text-right text-xs text-muted sm:block">{new Date().toLocaleDateString("en-NG", { weekday: "long", day: "numeric", month: "short", year: "numeric" })}<br /><Link href={`/s/${store.slug}`} className="mt-1 inline-flex items-center gap-1 font-bold text-kola">Open storefront <ExternalLink size={12} /></Link></div>
    </header>
    {reminder && <div className="rounded-[20px] bg-amber-50 p-4 text-sm text-warning"><p className="font-extrabold">Your Sella renewals are coming up</p><p className="mt-1 leading-6">{reminder.body}</p><div className="mt-3 flex flex-wrap gap-3"><Link href="/dashboard/billing" className="font-bold underline">Manage plan</Link><Link href="/dashboard/verification-badge" className="font-bold underline">Manage checkmark</Link></div></div>}
    {store.approval_status === "pending" && <div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-warning"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-warning" /><div><p className="text-sm font-extrabold">Your store is being reviewed</p><p className="mt-1 text-xs leading-5">After approval, your free Starter plan includes up to 40 active product listings.</p></div></div>}
    {store.approval_status === "rejected" && <div className="rounded-2xl bg-red-50 p-4 text-danger"><p className="text-sm font-extrabold">Your store needs an update</p><p className="mt-1 text-xs leading-5">{store.rejection_reason || "Review your store details and submit them again."}</p></div>}

    <section className="grid gap-4 overflow-hidden rounded-[26px] bg-kola-dark p-5 text-white sm:p-6 lg:grid-cols-[1fr_1.6fr]">
      <div className="relative"><p className="eyebrow text-lime">Today&apos;s focus</p><h2 className="display mt-2 max-w-xs text-2xl">Keep the buying experience moving.</h2><p className="mt-3 max-w-sm text-xs leading-5 text-white/70">Start with the work that gets orders out and customers coming back.</p><Link href="/dashboard/orders" className="btn mt-5 bg-lime text-kola-dark hover:bg-white">Open orders <ArrowRight size={15} /></Link></div>
      <div className="grid gap-2 sm:grid-cols-3">{priorities.map(({ label, value, href, icon: Icon, tone }) => <Link key={label} href={href} className="flex items-center gap-3 rounded-2xl bg-white/10 p-3.5 transition hover:bg-white/15"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white ${tone}`}><Icon size={17} /></span><span className="min-w-0"><b className="block text-xl leading-none">{value}</b><span className="mt-1 block text-[10px] leading-4 text-white/65">{label}</span></span><ChevronRight className="ml-auto shrink-0 text-white/45" size={15} /></Link>)}</div>
    </section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Paid sales" value={formatNaira(paidSales)} detail="Across all paid orders" icon={BarChart3} href="/dashboard/orders" accent /><Metric label="Orders to fulfil" value={openOrderCount || 0} detail="Pending, processing or shipped" icon={ShoppingBag} href="/dashboard/orders" /><Metric label="Live products" value={productCount || 0} detail={`${lowStockCount || 0} low stock`} icon={Package} href="/dashboard/products" /><Metric label="Wallet balance" value={formatNaira(wallet?.available)} detail="Available to withdraw" icon={WalletCards} href="/dashboard/wallet" /></section>

    <section className="app-card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-4 sm:px-5"><div><p className="eyebrow text-danger">Refund obligations</p><h2 className="mt-1 text-base font-extrabold">Outstanding refunds</h2><p className="mt-1 text-xs text-muted">Paid seller-side cancellations remain visible until the buyer receives the full original payment amount.</p></div><span className="chip">{refundRows?.length || 0} open</span></div>{refundRows?.length ? <div className="divide-y divide-line">{refundRows.map((refund) => <article key={refund.id} className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{refund.refund_reference} · Order #{refund.order_code}</p><p className="mt-1 text-xs text-muted">Buyer: {refund.buyer_name || "Buyer"} · Created {new Date(refund.created_at).toLocaleDateString("en-NG")}</p></div><div className="text-right"><p className="text-sm font-extrabold text-danger">{formatNaira(refund.refund_due)} due</p><p className="mt-1 text-[11px] text-muted">Outstanding contribution: {formatNaira(refund.outstanding_seller_contribution)}</p></div></div><p className="mt-3 text-xs leading-5 text-muted">Reason: {refund.cancellation_reason}</p><RefundActions refund={refund} /></article>)}</div> : <div className="p-7 text-center"><p className="text-sm font-extrabold">No outstanding refunds</p><p className="mt-1 text-xs text-muted">When a paid order is cancelled, Sella will show the full refund obligation here.</p></div>}</section>

    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <div className="app-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow text-kola">Money & momentum</p><h2 className="display mt-2 text-2xl">Your store at a glance</h2><p className="mt-2 text-xs text-muted">The numbers that matter for today&apos;s decisions.</p></div><Link href="/dashboard/analytics" className="btn-soft hidden text-xs sm:inline-flex">Analytics <ArrowRight size={14} /></Link></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-kola-light p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Paid sales</p><p className="mt-2 text-lg font-extrabold text-kola">{formatNaira(paidSales)}</p></div><div className="rounded-2xl bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Paid orders</p><p className="mt-2 text-lg font-extrabold">{paidOrderCount}</p></div><div className="rounded-2xl bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Completed</p><p className="mt-2 text-lg font-extrabold">{Number(store.completed_orders || 0)}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="text-xs text-muted">See what is converting</span><Link href="/dashboard/analytics" className="text-xs font-bold text-kola">Open analytics <ArrowRight size={14} className="inline" /></Link></div></div>
      <div className="app-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow text-kola">Subscription</p><h2 className="mt-2 text-base font-extrabold">Current plan</h2></div><Link href="/dashboard/billing" className="text-xs font-bold text-kola underline">Manage</Link></div><div className="mt-5 rounded-2xl border border-kola/30 bg-kola-light p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-extrabold">{planName}</p><p className="mt-1 text-xs text-muted">{activeSubscription ? `Active until ${new Date(activeSubscription.expires_at).toLocaleDateString("en-NG", { day: "numeric", month: "short", year: "numeric" })}` : "Free forever"}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-extrabold text-success">Active</span></div><p className="mt-5 border-t border-kola/15 pt-3 text-xs font-bold text-kola">{planLimit ? `Up to ${planLimit} active products` : "Unlimited active products"} · {planName === "Starter" ? "3.2%" : planName === "Basic" ? "2.8%" : planName === "Plus" ? "2.6%" : "2.4%"} commission</p></div><Link href="/dashboard/wallet" className="mt-4 flex items-center justify-between rounded-xl bg-surface px-3 py-3 text-xs font-bold">Available to withdraw <span className="text-kola">{formatNaira(wallet?.available)} <ArrowRight size={13} className="inline" /></span></Link></div>
    </section>

    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="app-card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-4 py-4 sm:px-5"><div><p className="eyebrow text-kola">Operations</p><h2 className="mt-1 text-base font-extrabold">Recent orders</h2></div><Link href="/dashboard/orders" className="text-xs font-bold text-kola">View all <ArrowRight size={14} className="inline" /></Link></div>{recentOrders?.length ? recentOrders.map((order) => <Link key={order.id} href={`/dashboard/orders?order=${order.id}`} className="flex items-center gap-3 border-b border-line px-4 py-3.5 last:border-0 hover:bg-surface sm:px-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-surface text-kola"><Package size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">#{order.order_code} · {order.customers?.name || "Customer"}</p><p className="mt-0.5 text-[11px] text-muted">{new Date(order.created_at).toLocaleDateString("en-NG", { day: "numeric", month: "short" })} · {order.payment_status}</p></div><div className="text-right"><p className="text-sm font-extrabold">{formatNaira(order.total)}</p><div className="mt-1"><StatusPill status={order.status} /></div></div><ChevronRight size={15} className="text-muted" /></Link>) : <p className="p-8 text-center text-sm text-muted">Your orders will show here after checkout.</p>}</div>
      <div className="app-card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-4 py-4 sm:px-5"><div><p className="eyebrow text-warning">Inventory watch</p><h2 className="mt-1 text-base font-extrabold">Low stock products</h2></div><Link href="/dashboard/products" className="text-xs font-bold text-kola">Manage stock</Link></div>{lowStockProducts?.length ? lowStockProducts.map((product) => <Link key={product.id} href={`/dashboard/products/${product.id}`} className="flex items-center gap-3 border-b border-line px-4 py-3 last:border-0"><div className="relative h-9 w-9 shrink-0 overflow-hidden rounded-xl bg-surface">{product.image_urls?.[0] && <Image src={product.image_urls[0]} alt="" fill sizes="36px" className="object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{product.name}</p><p className="mt-1 text-[10px] text-danger">{product.stock || 0} left · {formatNaira(product.price)}</p></div><span className="text-[10px] font-bold text-kola">Restock <ArrowRight size={12} className="inline" /></span></Link>) : <p className="p-8 text-center text-sm text-muted">No low-stock products.</p>}</div></section>

    <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className="app-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow text-kola">Storefront access</p><h2 className="mt-2 text-base font-extrabold">Bring buyers to your shop</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-kola-light text-kola"><Share2 size={18} /></span></div><p className="mt-3 text-xs leading-5 text-muted">Your seller code is a simple way for buyers to find and trust your store.</p><p className="mt-4 rounded-xl bg-kola-light px-4 py-3 text-center text-xl font-extrabold tracking-[.18em] text-kola">{store.seller_code || "Generating…"}</p><CopyStoreLink url={storeLink} /><Link href={`/s/${store.slug}`} className="btn-soft mt-3 flex w-full text-xs">View storefront <ExternalLink size={15} /></Link></div><ShareStore url={storeLink} storeName={store.name} sellerCode={store.seller_code} /></section>

    <section><div className="flex items-end justify-between"><div><p className="eyebrow text-kola">Store health</p><h2 className="display mt-1 text-xl">Finish your setup</h2></div><Sparkles size={20} className="text-kola" /></div><div className="app-card mt-4 grid gap-0 sm:grid-cols-3">{[{ done: (productCount || 0) > 0, label: "Add your first product", href: "/dashboard/products/new" }, { done: !!store.logo_url, label: "Add your store logo", href: "/dashboard/settings" }, { done: !!store.whatsapp, label: "Add WhatsApp contact", href: "/dashboard/settings" }].map((item, index) => <Link key={item.label} href={item.href} className={`flex items-center gap-3 p-4 ${index ? "border-t border-line sm:border-l sm:border-t-0" : ""}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${item.done ? "bg-kola text-white" : "border-2 border-line text-transparent"}`}>{item.done && <Check size={14} />}</span><span className={`text-xs font-bold ${item.done ? "text-muted line-through" : "text-ink"}`}>{item.label}</span><ChevronRight size={15} className="ml-auto text-muted" /></Link>)}</div></section>
  </div>;
}
