import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Check, ChevronRight, Package, ShieldCheck, ShoppingBag, TrendingUp, Users, WalletCards } from "lucide-react";
import { getMyStore } from "@/lib/store";
import { formatNaira, storeUrl } from "@/lib/utils";
import { SITE_URL } from "@/lib/config";
import ShareStore from "@/components/ShareStore";
import CopyStoreLink from "@/components/CopyStoreLink";

function StatusPill({ status }) { const tone = status === "delivered" ? "bg-green-50 text-success" : status === "cancelled" ? "bg-red-50 text-danger" : "bg-amber-50 text-warning"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ${tone}`}>{status}</span>; }
function Metric({ label, value, detail, icon: Icon, href, accent = false }) { return <Link href={href} className={`app-card min-w-0 p-4 transition hover:-translate-y-0.5 sm:p-5 ${accent ? "border-kola/20 bg-kola-light" : ""}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${accent ? "bg-kola text-white" : "bg-surface text-kola"}`}><Icon size={17} /></span><p className="mt-4 truncate text-xs font-bold text-muted">{label}</p><p className="mt-1 truncate text-2xl font-extrabold text-ink">{value}</p><p className="mt-1 truncate text-[10px] text-muted">{detail}</p></Link>; }

export default async function DashboardHome() {
  const { supabase, store } = await getMyStore();
  const [{ count: productCount }, { count: lowStockCount }, { count: openOrderCount }, { data: recentOrders }, { data: wallet }, { data: activeSubscription }, { data: paidRows }, { data: lowStockProducts }] = await Promise.all([
    supabase.from("products").select("id", { count: "exact", head: true }).eq("store_id", store.id).eq("is_active", true),
    supabase.from("products").select("id", { count: "exact", head: true }).eq("store_id", store.id).eq("is_active", true).lte("stock", 3),
    supabase.from("orders").select("id", { count: "exact", head: true }).eq("store_id", store.id).in("status", ["pending", "processing", "shipped"]),
    supabase.from("orders").select("id,order_code,total,status,payment_status,created_at,customers(name)").eq("store_id", store.id).order("created_at", { ascending: false }).limit(5),
    supabase.from("wallets").select("available").eq("store_id", store.id).maybeSingle(),
    supabase.from("subscriptions").select("plan,expires_at,status").eq("store_id", store.id).in("status", ["paid", "active"]).gt("expires_at", new Date().toISOString()).order("expires_at", { ascending: false }).limit(1).maybeSingle(),
    supabase.from("orders").select("total").eq("store_id", store.id).eq("payment_status", "paid").limit(1000),
    supabase.from("products").select("id,name,stock,price,image_urls").eq("store_id", store.id).eq("is_active", true).lte("stock", 3).order("stock", { ascending: true }).limit(5),
  ]);
  const paidSales = (paidRows || []).reduce((sum, row) => sum + Number(row.total || 0), 0);
  const planName = activeSubscription ? ({ basic: "Basic", plus: "Plus", premium: "Premium", quarterly: "Basic", biannual: "Plus", yearly: "Premium" }[activeSubscription.plan] || activeSubscription.plan) : "Starter";
  const planLimit = { Starter: 40, Basic: 150, Plus: 500, Premium: null }[planName];
  const storeLink = storeUrl(SITE_URL, store.slug);
  return <div className="space-y-7 sm:space-y-9">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-kola">Seller workspace</p><h1 className="display mt-2 text-3xl sm:text-4xl">Good morning, {store.name}.</h1><p className="mt-2 text-sm text-muted">Here&apos;s what&apos;s happening with your store today.</p></div><p className="hidden text-right text-xs text-muted sm:block">{new Date().toLocaleDateString("en-NG", { weekday: "short", day: "numeric", month: "short", year: "numeric" })}<br /><span className="mt-1 inline-block font-bold">Keep your store moving.</span></p></header>
    {store.approval_status === "pending" && <div className="flex items-start gap-3 rounded-2xl bg-amber-50 p-4 text-warning"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-warning" /><div><p className="text-sm font-extrabold">Your store is being reviewed</p><p className="mt-1 text-xs leading-5">After approval, your free Starter plan includes up to 40 active product listings.</p></div></div>}
    {store.approval_status === "rejected" && <div className="rounded-2xl bg-red-50 p-4 text-danger"><p className="text-sm font-extrabold">Your store needs an update</p><p className="mt-1 text-xs leading-5">{store.rejection_reason || "Review your store details and submit them again."}</p></div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Paid sales" value={formatNaira(paidSales)} detail="All paid orders" icon={BarChart3} href="/dashboard/orders" accent /><Metric label="Orders to fulfil" value={openOrderCount || 0} detail="Pending, processing or shipped" icon={ShoppingBag} href="/dashboard/orders" /><Metric label="Products" value={productCount || 0} detail={`${lowStockCount || 0} low stock`} icon={Package} href="/dashboard/products" /><Metric label="Wallet balance" value={formatNaira(wallet?.available)} detail="Available to withdraw" icon={WalletCards} href="/dashboard/wallet" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="app-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-kola">Sales overview</p><h2 className="display mt-2 text-2xl">Your store at a glance</h2><p className="mt-2 text-xs leading-5 text-muted">Paid sales and live activity from your Sella store.</p></div><BarChart3 className="text-kola" size={22} /></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl bg-kola-light p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Paid sales</p><p className="mt-2 text-xl font-extrabold text-kola">{formatNaira(paidSales)}</p></div><div className="rounded-xl bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Paid orders</p><p className="mt-2 text-xl font-extrabold">{paidRows?.length || 0}</p></div><div className="rounded-xl bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Completed</p><p className="mt-2 text-xl font-extrabold">{Number(store.completed_orders || 0)}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="text-xs text-muted">Need a deeper view?</span><Link href="/dashboard/analytics" className="text-xs font-bold text-kola">Open analytics <ArrowRight size={14} className="inline" /></Link></div></div><div className="app-card p-5"><div className="flex items-center justify-between"><h2 className="text-base font-extrabold">Current plan</h2><Link href="/dashboard/billing" className="text-xs font-bold text-kola underline">Manage plan</Link></div><div className="mt-4 rounded-2xl border border-kola/40 bg-kola-light p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-extrabold">{planName}</p><p className="mt-1 text-xs text-muted">{activeSubscription ? `Active until ${new Date(activeSubscription.expires_at).toLocaleDateString("en-NG", { day: "numeric", month: "short", year: "numeric" })}` : "Free forever"}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-extrabold text-success">Active</span></div><p className="mt-4 border-t border-kola/15 pt-3 text-xs font-bold text-kola">{planLimit ? `Up to ${planLimit} active products` : "Unlimited active products"} · {planName === "Starter" ? "3.2%" : planName === "Basic" ? "2.8%" : planName === "Plus" ? "2.6%" : "2.4%"} commission</p></div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="app-card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-4 py-4"><h2 className="text-base font-extrabold">Recent orders</h2><Link href="/dashboard/orders" className="text-xs font-bold text-kola">View all <ArrowRight size={14} className="inline" /></Link></div>{recentOrders?.length ? recentOrders.map((order) => <Link key={order.id} href={`/dashboard/orders?order=${order.id}`} className="flex items-center gap-3 border-b border-line px-4 py-3.5 last:border-0 hover:bg-surface"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-surface text-kola"><Package size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">#{order.order_code} · {order.customers?.name || "Customer"}</p><p className="mt-0.5 text-[11px] text-muted">{new Date(order.created_at).toLocaleDateString("en-NG", { day: "numeric", month: "short" })} · {order.payment_status}</p></div><div className="text-right"><p className="text-sm font-extrabold">{formatNaira(order.total)}</p><div className="mt-1"><StatusPill status={order.status} /></div></div><ChevronRight size={15} className="text-muted" /></Link>) : <p className="p-8 text-center text-sm text-muted">Your orders will show here after checkout.</p>}</div><div className="app-card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-4 py-4"><h2 className="text-base font-extrabold">Low stock products</h2><Link href="/dashboard/products" className="text-xs font-bold text-kola">View all</Link></div>{lowStockProducts?.length ? lowStockProducts.map((product) => <Link key={product.id} href={`/dashboard/products/${product.id}`} className="flex items-center gap-3 border-b border-line px-4 py-3 last:border-0"><div className="relative h-9 w-9 shrink-0 overflow-hidden rounded-xl bg-surface">{product.image_urls?.[0] && <Image src={product.image_urls[0]} alt="" fill sizes="36px" className="object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{product.name}</p><p className="mt-1 text-[10px] text-danger">{product.stock || 0} left</p></div><span className="text-[10px] font-bold text-kola">Restock</span></Link>) : <p className="p-8 text-center text-sm text-muted">No low-stock products.</p>}</div></section>
    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className="app-card p-5"><div className="flex items-center justify-between"><div><p className="eyebrow text-kola">Storefront</p><h2 className="mt-2 text-base font-extrabold">Share your store</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-kola-light text-kola"><ShieldCheck size={18} /></span></div><p className="mt-3 text-xs leading-5 text-muted">Buyers can use your store ID or link to open your store, trust it and shop.</p><p className="mt-4 rounded-xl bg-kola-light px-4 py-3 text-center text-xl font-extrabold tracking-[.18em] text-kola">{store.seller_code || "Generating…"}</p><CopyStoreLink url={storeLink} /><Link href={`/s/${store.slug}`} className="btn-soft mt-3 flex w-full text-xs">View storefront <ArrowRight size={15} /></Link></div><div><ShareStore url={storeLink} storeName={store.name} sellerCode={store.seller_code} /></div></section>
    <section><p className="eyebrow text-kola">Setup</p><h2 className="display mt-1 text-xl">Finish your setup</h2><div className="app-card mt-4 grid gap-0 sm:grid-cols-3">{[{ done: (productCount || 0) > 0, label: "Add your first product", href: "/dashboard/products/new" }, { done: !!store.logo_url, label: "Add your store logo", href: "/dashboard/settings" }, { done: !!store.whatsapp, label: "Add WhatsApp contact", href: "/dashboard/settings" }].map((item, index) => <Link key={item.label} href={item.href} className={`flex items-center gap-3 p-4 ${index ? "border-t border-line sm:border-l sm:border-t-0" : ""}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${item.done ? "bg-kola text-white" : "border-2 border-line text-transparent"}`}>{item.done && <Check size={14} />}</span><span className={`text-xs font-bold ${item.done ? "text-muted line-through" : "text-ink"}`}>{item.label}</span><ChevronRight size={15} className="ml-auto text-muted" /></Link>)}</div></section>
  </div>;
}
