import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { formatNaira } from "@/lib/utils";
import ReportForm from "@/components/ReportForm";

export default async function OrderDetailPage({ params }) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: order } = await supabase.from("orders").select("*,stores(name,slug,whatsapp,phone),customers(name,phone,email,address),order_items(id,name,price,quantity)").eq("id", params.id).eq("buyer_id", user.id).maybeSingle();
  if (!order) notFound();
  return <div className="mx-auto max-w-2xl"><Link href="/account/orders" className="text-sm font-semibold text-kola">← My orders</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted">{order.stores?.name}</p><h1 className="mt-1 text-3xl font-bold">Order #{order.order_number}</h1></div><span className="rounded-full bg-kola-light px-3 py-1 text-sm font-semibold capitalize text-kola">{order.status}</span></div><div className="mt-8 panel"><h2 className="font-semibold">Items</h2><div className="mt-4 divide-y divide-line">{order.order_items?.map((item) => <div key={item.id} className="flex justify-between py-3"><span>{item.quantity} × {item.name}</span><span className="font-semibold">{formatNaira(item.price * item.quantity)}</span></div>)}</div><div className="mt-4 flex justify-between border-t border-line pt-4 text-lg font-bold"><span>Total</span><span>{formatNaira(order.total)}</span></div></div>{order.payment_status === "unpaid" && <div className="mt-4 rounded-2xl border border-mango bg-[#FFF8E7] p-5"><h2 className="font-semibold">Payment pending</h2>{order.payment_account_number ? <p className="mt-2 text-sm">Transfer to <strong>{order.payment_bank_name || "the assigned bank"}</strong> account <strong>{order.payment_account_number}</strong>. Your order will update automatically after confirmation.</p> : <p className="mt-2 text-sm">Payment instructions will appear when the store connects TransactPay.</p>}</div>}{order.payment_status === "paid" && order.delivery_code && order.escrow_status === "held" && <div className="mt-4 rounded-2xl bg-kola p-5 text-center text-white"><p className="text-sm opacity-80">Only show this code after you receive your order</p><p className="mt-2 text-4xl font-bold tracking-[0.4em]">{order.delivery_code}</p><p className="mt-3 text-sm opacity-80">The seller enters this code to confirm delivery and release payment.</p></div>}<div className="mt-4 panel"><h2 className="font-semibold">Fulfilment</h2><p className="mt-2 text-sm text-muted">{order.fulfilment_method === "pickup" ? "Pickup" : `Delivery to ${order.customers?.address || "the address provided at checkout"}`}</p><p className="mt-4 text-sm text-muted">The seller will contact you at {order.customers?.phone || order.customers?.email} to arrange the next step.</p></div><div className="mt-4 panel"><h2 className="font-semibold">Report this order</h2><p className="mt-1 text-sm text-muted">If there is a problem, report it before delivery funds are released.</p><div className="mt-4"><ReportForm storeId={order.store_id} orderId={order.id} /></div></div></div>;
}
