import { createClient } from "@/lib/supabase/server";
import { ensureBuyerWallet } from "@/lib/buyer";
import { formatNaira } from "@/lib/utils";

export default async function WalletPage() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const wallet = await ensureBuyerWallet(user);
  const { data: transactions } = wallet ? await supabase.from("buyer_wallet_transactions").select("id,amount,label,created_at").eq("buyer_wallet_id", wallet.id).order("created_at", { ascending: false }).limit(10) : { data: [] };
  return <div className="mx-auto max-w-2xl"><p className="text-sm font-semibold text-kola">Buyer wallet</p><h1 className="mt-1 text-3xl font-bold">Your Sella wallet</h1><div className="mt-6 rounded-3xl bg-kola p-6 text-white"><p className="text-sm opacity-80">Available balance</p><p className="mt-2 text-4xl font-bold">{formatNaira(wallet?.balance)}</p></div>{wallet?.dedicated_account_number ? <div className="mt-5 panel"><h2 className="font-semibold">Fund your wallet by bank transfer</h2><p className="mt-2 text-sm text-muted">Transfer any amount to your dedicated account. TransactPay will credit your wallet automatically after the payment is confirmed.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-muted">Bank</p><p className="mt-1 font-semibold">{wallet.dedicated_bank_name || "TransactPay partner bank"}</p></div><div><p className="text-xs uppercase tracking-wide text-muted">Account number</p><p className="mt-1 text-xl font-bold tracking-wide">{wallet.dedicated_account_number}</p></div></div>{wallet.dedicated_account_name && <p className="mt-3 text-sm text-muted">Account name: {wallet.dedicated_account_name}</p>}</div> : <div className="mt-5 rounded-2xl border border-mango bg-[#FFF8E7] p-5 text-sm">Your dedicated funding account will appear here after TransactPay is configured.</div>}<section className="mt-8"><h2 className="text-xl font-bold">Recent activity</h2><div className="mt-4 divide-y divide-line rounded-2xl border border-line bg-white">{transactions?.length ? transactions.map((txn) => <div key={txn.id} className="flex justify-between p-4"><div><p className="font-medium">{txn.label}</p><p className="mt-1 text-xs text-muted">{new Date(txn.created_at).toLocaleString()}</p></div><p className={`font-bold ${txn.amount > 0 ? "text-kola" : ""}`}>{txn.amount > 0 ? "+" : ""}{formatNaira(txn.amount)}</p></div>) : <p className="p-5 text-sm text-muted">No wallet activity yet.</p>}</div></section></div>;
}
